# Generated by Django 4.0.6 on 2022-08-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agg', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
